drivers: gpu: drm: msm: fix dsi_panel build for gcc
Signed-off-by: Pulkit077 <pulkitagarwal2k1@gmail.com>

[vbajs]
* ximi is so obessed with floating-point types it's insane

In function 'dc_set_backlight',
    inlined from 'dsi_panel_set_backlight' at ../drivers/gpu/drm/msm/dsi-staging/dsi_panel.c:978:6:
../drivers/gpu/drm/msm/dsi-staging/dsi_panel.c:929:26: error: '-mgeneral-regs-only' is incompatible with the use of floating-point types
  929 |                 crcValue = 0.5 + mDCBLCoeff[0] * bl_lvl + mDCBLCoeff[1]; //0.5 is for roundin
      |                 ~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

* Also, just removing -mgeneral-regs-only is enough. -mno-implicit-float
  does not exist on gcc. It could be intended for clang but better
  revert https://github.com/LineageOS/android_kernel_xiaomi_sm6150/commit/59f24c4046f73d88ccb87ed62c70304bc1eaebe6 instead.